tcms/bugs/urls.py
# Copyright (c) 2019-2020 Alexander Todorov <atodorov@MrSenko.com>

# Licensed under the GPL 2.0: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html

from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r"^(?P<pk>\d+)/$", views.Get.as_view(), name="bugs-get"),
    re_path(r"^new/$", views.New.as_view(), name="bugs-new"),
    re_path(r"^(?P<pk>\d+)/edit/$", views.Edit.as_view(), name="bugs-edit"),
    re_path(r"^search/$", views.Search.as_view(), name="bugs-search"),
    re_path(r"^comment/$", views.AddComment.as_view(), name="bugs-comment"),
]

tcms/kiwi_auth/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.contrib.auth import views as contrib_auth_views
from django.urls import path, re_path, reverse_lazy

from tcms.kiwi_auth import views

urlpatterns = [
    re_path(
        r"^(?P<pk>\d+)/profile/$",
        views.Profile.as_view(),
        name="tcms-profile",
    ),
    re_path(
        r"^confirm/(?P<activation_key>[A-Za-z0-9\-]+)/$",
        views.Confirm.as_view(),
        name="tcms-confirm",
    ),
    re_path(
        r"^login/$", views.LoginViewWithCustomTemplate.as_view(), name="tcms-login"
    ),
    re_path(
        r"^logout/$",
        contrib_auth_views.LogoutView.as_view(next_page=reverse_lazy("tcms-login")),
        name="tcms-logout",
    ),
    re_path(
        r"^passwordreset/$",
        views.PasswordResetView.as_view(),
        name="tcms-password_reset",
    ),
    re_path(
        r"^passwordreset/done/$",
        contrib_auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "passwordreset/confirm/<uidb64>/<token>/",
        contrib_auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    re_path(
        r"^passwordreset/complete/$",
        contrib_auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    re_path(
        r"^(?P<pk>\d+)/reset-user-email/$",
        views.ResetUserEmail.as_view(),
        name="reset-user-email",
    ),
    re_path(
        r"^admin-users/$",
        views.UsersRouter.as_view(),
        name="admin-users-router",
    ),
    re_path(
        r"^admin-groups/$",
        views.GroupsRouter.as_view(),
        name="admin-groups-router",
    ),
]

if settings.REGISTRATION_ENABLED:
    urlpatterns.append(
        re_path(r"^register/$", views.Register.as_view(), name="tcms-register")
    )

tcms/testruns/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r"^new/$", views.NewTestRunView.as_view(), name="testruns-new"),
    re_path(r"^(?P<pk>\d+)/$", views.GetTestRunView.as_view(), name="testruns-get"),
    re_path(
        r"^(?P<pk>\d+)/clone/$", views.CloneTestRunView.as_view(), name="testruns-clone"
    ),
    re_path(
        r"^(?P<pk>\d+)/edit/$", views.EditTestRunView.as_view(), name="testruns-edit"
    ),
    re_path(
        r"^from-plan/(?P<plan_id>\d+)/$",
        views.NewFromPlan.as_view(),
        name="testruns-from-plan",
    ),
    re_path(r"^search/$", views.SearchTestRunView.as_view(), name="testruns-search"),
    re_path(
        r"^environment/(?P<pk>\d+)/$",
        views.GetEnvironment.as_view(),
        name="testruns-environment",
    ),
]

tcms/urls.py
# -*- coding: utf-8 -*-
from importlib import import_module

import pkg_resources
from attachments import urls as attachments_urls
from captcha import urls as captcha_urls
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import re_path
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog
from grappelli import urls as grappelli_urls
from modernrpc.core import Protocol
from modernrpc.views import RPCEntryPoint

from tcms.core import views as core_views
from tcms.kiwi_auth import urls as auth_urls
from tcms.telemetry import urls as telemetry_urls
from tcms.testcases import urls as testcases_urls
from tcms.testplans import urls as testplans_urls
from tcms.testruns import urls as testruns_urls

urlpatterns = [
    re_path(r"^$", core_views.DashboardView.as_view(), name="core-views-index"),
    re_path(r"^captcha/", include(captcha_urls)),
    re_path(r"^xml-rpc/", RPCEntryPoint.as_view(protocol=Protocol.XML_RPC)),
    re_path(r"^json-rpc/$", RPCEntryPoint.as_view(protocol=Protocol.JSON_RPC)),
    re_path(r"^init-db/$", core_views.InitDBView.as_view(), name="init-db"),
    re_path(
        r"^translation-mode/",
        core_views.TranslationMode.as_view(),
        name="translation-mode",
    ),
    re_path(r"^grappelli/", include(grappelli_urls)),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^attachments/", include(attachments_urls, namespace="attachments")),
    # Account information zone, such as login method
    re_path(r"^accounts/", include(auth_urls)),
    # Testplans zone
    re_path(r"^plan/", include(testplans_urls)),
    # Testcases zone
    re_path(r"^case/", include(testcases_urls.case_urls)),
    re_path(r"^cases/", include(testcases_urls.cases_urls)),
    # Testruns zone
    re_path(r"^runs/", include(testruns_urls)),
    re_path(r"^telemetry/", include(telemetry_urls)),
    # JavaScript translations, see
    # https://docs.djangoproject.com/en/2.1/topics/i18n/translation/#django.views.i18n.JavaScriptCatalog
    re_path(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
]


# conditional import b/c this App can be disabled
if "tcms.bugs.apps.AppConfig" in settings.INSTALLED_APPS:
    from tcms.bugs import urls as bugs_urls

    urlpatterns.append(re_path(r"^bugs/", include(bugs_urls)))


for plugin in pkg_resources.iter_entry_points("kiwitcms.plugins"):
    plugin_urls = import_module(f"{plugin.module_name}.urls")
    urlpatterns.append(re_path(f"^{plugin.name}/", include(plugin_urls)))


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.extend(
        [
            re_path(r"^500/$", TemplateView.as_view(template_name="500.html")),
            re_path(r"^404/$", TemplateView.as_view(template_name="404.html")),
        ]
    )


# Overwrite default 500 handler
# More details could see django.core.urlresolvers._resolve_special()
handler500 = "tcms.core.views.server_error"

tcms/bugs/models.py
# Copyright (c) 2019-2022 Alexander Todorov <atodorov@MrSenko.com>

# Licensed under the GPL 2.0: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html

from colorfield.fields import ColorField
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from tcms.core.models.base import UrlMixin


class Severity(models.Model):
    name = models.CharField(max_length=64, unique=True)
    weight = models.IntegerField(default=0)
    icon = models.CharField(max_length=64)
    color = ColorField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = _("Severity")


class Bug(models.Model, UrlMixin):
    summary = models.CharField(max_length=255, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    # True means bug is still open
    status = models.BooleanField(default=True, db_index=True)

    reporter = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="repoted_bugs"
    )
    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="assigned_bugs",
        null=True,
        blank=True,
    )

    product = models.ForeignKey("management.Product", on_delete=models.CASCADE)
    version = models.ForeignKey("management.Version", on_delete=models.CASCADE)
    build = models.ForeignKey("management.Build", on_delete=models.CASCADE)
    severity = models.ForeignKey(
        Severity, on_delete=models.CASCADE, blank=True, null=True
    )

    executions = models.ManyToManyField("testruns.TestExecution", related_name="bugs")
    tags = models.ManyToManyField("management.Tag", related_name="bugs")

    def __str__(self):
        return f"BUG-{self.pk}: {self.summary} "

    def _get_absolute_url(self):
        return reverse(
            "bugs-get",
            args=[
                self.pk,
            ],
        )

    def get_absolute_url(self):
        return self._get_absolute_url()

tcms/core/models/abstract.py
from django.db import models


class Property(models.Model):
    name = models.CharField(max_length=255)
    value = models.CharField(max_length=255)

    class Meta:
        abstract = True

    def __str__(self):
        return f"{self.name}: {self.value}"

tcms/bugs/forms.py
# Copyright (c) 2019,2022,2025-2026 Alexander Todorov <atodorov@MrSenko.com>

# Licensed under the GPL 2.0: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html

from django import forms
from django.utils.translation import gettext_lazy as _

from tcms.bugs.models import Bug, Severity
from tcms.core.forms.fields import UserField
from tcms.core.widgets import SimpleMDE
from tcms.management.models import Build, Version
from tcms.rpc.api.forms import DateTimeFieldWithDefault


class NewBugForm(forms.ModelForm):
    class Meta:
        model = Bug
        fields = [
            "summary",
            "assignee",
            "reporter",
            "product",
            "version",
            "build",
            "severity",
        ]

    assignee = UserField(required=False)

    text = forms.CharField(
        widget=SimpleMDE(),
        required=False,
        initial=_(
            """Description of problem:


How often reproducible:


Steps to Reproduce:
1.
2.
3.

Actual results:


Expected results:


Additional info:"""
        ),
    )

    def populate(self, product_id=None):
        if product_id:
            self.fields["version"].queryset = Version.objects.filter(
                product_id=product_id
            )
            self.fields["build"].queryset = Build.objects.filter(
                version__product=product_id
            )
        else:
            self.fields["version"].queryset = Version.objects.all()
            self.fields["build"].queryset = Build.objects.all()


class NewBugFromRPCForm(forms.ModelForm):
    created_at = DateTimeFieldWithDefault(required=False)

    class Meta:
        model = Bug
        exclude = (  # pylint: disable=modelform-uses-exclude
            "tags",
            "executions",
        )


class BugCommentForm(forms.Form):  # pylint: disable=must-inherit-from-model-form
    bug = forms.ModelChoiceField(
        queryset=Bug.objects.all(),
    )

    text = forms.CharField(
        widget=SimpleMDE(),
        required=False,
    )

    def populate(self, bug_id):
        self.fields["bug"].queryset = Bug.objects.filter(pk=bug_id)


class SeverityForm(forms.ModelForm):
    class Meta:
        model = Severity
        fields = "__all__"

tcms/core/contrib/linkreference/forms.py
from django import forms

from tcms.core.contrib.linkreference.models import LinkReference


class LinkReferenceForm(forms.ModelForm):
    class Meta:
        model = LinkReference
        exclude = ["created_on"]  # pylint: disable=modelform-uses-exclude

tcms/core/forms/fields.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db.models import Q

User = get_user_model()  # pylint: disable=invalid-name


class UserField(forms.CharField):
    """
    Custom field type.
    Will eventually support user selection
    """

    def clean(self, value):
        """
        Form-validation:  accept a string/integer.
        Looks at both email address and real name.
        """
        if value == "" or value is None:
            if self.required:
                raise ValidationError("A user name or user ID is required.")
            return None
        if isinstance(value, int):
            try:
                return User.objects.get(pk=value)
            except User.DoesNotExist:
                raise ValidationError(f'Unknown user_id: "{value}"') from None
        else:
            value = value.strip()
            if value.isdigit():
                try:
                    return User.objects.get(pk=value)
                except User.DoesNotExist:
                    raise ValidationError(f'Unknown user_id: "{value}"') from None
            else:
                try:
                    return User.objects.get((Q(email=value) | Q(username=value)))
                except User.DoesNotExist:
                    raise ValidationError(f'Unknown user: "{value}"') from None

tcms/kiwi_auth/forms.py
# -*- coding: utf-8 -*-
from captcha import fields
from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordResetForm as DjangoPasswordResetForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.models import Site
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.utils.translation import override

from tcms.core.utils import request_host_link
from tcms.core.utils.mailto import custom_email_validators, mailto
from tcms.kiwi_auth.models import UserActivationKey
from tcms.utils.permissions import initiate_user_with_default_setups

User = get_user_model()  # pylint: disable=invalid-name


class CustomCaptchaTextInput(fields.CaptchaTextInput):
    template_name = "captcha_field.html"


def validate_email_already_in_use(email):
    if User.objects.filter(email__iexact=email.strip()).exists():
        raise forms.ValidationError(_("A user with that email already exists."))


def set_activation_key_for(user):
    return UserActivationKey.set_random_key_for_user(user=user)


@override(settings.LANGUAGE_CODE)
def send_confirmation_email_to(user, request, activation_key):
    current_site = Site.objects.get(pk=settings.SITE_ID)
    confirm_url = request_host_link(request, current_site.domain) + reverse(
        "tcms-confirm",
        args=[
            activation_key.activation_key,
        ],
    )

    mailto(
        template_name="email/confirm_registration.txt",
        recipients=[user.email],
        subject=_("Please confirm your Kiwi TCMS account email address"),
        context={
            "user": user,
            "confirm_url": confirm_url,
        },
    )


class RegistrationForm(UserCreationForm):  # pylint: disable=too-many-ancestors
    email = forms.EmailField(
        validators=[validate_email_already_in_use, custom_email_validators],
    )
    captcha = (
        fields.CaptchaField(
            widget=CustomCaptchaTextInput(attrs={"class": "form-control"})
        )
        if settings.USE_CAPTCHA
        else None
    )

    class Meta:
        model = User
        fields = ("username",)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.is_active = False
        user.set_password(self.cleaned_data["password1"])

        if User.objects.filter(is_superuser=True).count() == 0:
            user.is_superuser = True
            user.is_active = True

        if commit:
            user.save()
            initiate_user_with_default_setups(user)
        return user


class PasswordResetForm(
    DjangoPasswordResetForm
):  # pylint: disable=must-inherit-from-model-form
    """
    Overrides the default form b/c it uses Site.objects.get_current()
    which uses an internal cache and produces wrong results when
    kiwitcms-tenants is installed.
    """

    captcha = (
        fields.CaptchaField(
            widget=CustomCaptchaTextInput(attrs={"class": "form-control"})
        )
        if settings.USE_CAPTCHA
        else None
    )

    def save(  # pylint: disable=too-many-arguments,too-many-positional-arguments
        self,
        domain_override=None,
        subject_template_name="registration/password_reset_subject.txt",
        email_template_name="registration/password_reset_email.html",
        use_https=False,
        token_generator=default_token_generator,
        from_email=None,
        request=None,
        html_email_template_name=None,
        extra_email_context=None,
    ):
        current_site = Site.objects.get(pk=settings.SITE_ID)
        # call the stock method and just overrides the domain
        super().save(
            current_site.domain,
            subject_template_name,
            email_template_name,
            use_https,
            token_generator,
            from_email,
            request,
            html_email_template_name,
            extra_email_context,
        )


class ResetUserEmailForm(forms.Form):  # pylint: disable=must-inherit-from-model-form
    email_1 = forms.EmailField(
        validators=[validate_email_already_in_use, custom_email_validators],
    )
    email_2 = forms.EmailField()

    def clean_email_2(self):
        email_01 = self.cleaned_data.get("email_1")
        email_02 = self.cleaned_data.get("email_2")
        if email_01 and email_02 and email_01 != email_02:
            raise forms.ValidationError(_("Email mismatch"))
        return email_02

tcms/management/forms.py
# -*- coding: utf-8 -*-

from django import forms

from tcms.management.models import Version


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ["product", "value"]

tcms/rpc/api/forms/testexecution.py
from django import forms

from tcms.core.contrib.linkreference.models import LinkReference


class LinkReferenceForm(forms.ModelForm):
    class Meta:
        model = LinkReference
        fields = "__all__"

tcms/templates/include/ads.html
{% if not REQUEST__NONAV %}
    <script async src="https://media.ethicalads.io/media/client/ethicalads.min.js"></script>
    <div data-ea-publisher="kiwitcms-container" data-ea-type="text" data-ea-style="fixedfooter"></div>
{% endif %}

tcms/templates/include/attachments.html
{% load i18n %}
{% load attachments_tags %}

<div class="card-pf card-pf-accented">
    <h2 class="card-pf-title">
        <span class="fa fa-paperclip"></span>
        {% if card_title %}
            {{ card_title }}
        {% else %}
            {% trans 'Attachments' %}
        {% endif %}
    </h2>

    <div class="card-pf-body">
        <table class="table" id="attachments">
            <thead>
            <tr>
                <th>{% trans 'File' %}</th>
                <th>{% trans 'Owner' %}</th>
                <th>{% trans 'Date' %}</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% get_attachments_for object as attachments_list %}
            {% for attachment in attachments_list %}
            <tr>
                <td><a href="{{ attachment.attachment_file.url }}">{{ attachment.filename }}</a></td>
                <td><a href="{% url 'tcms-profile' attachment.creator.pk %}">{{ attachment.creator }}</a></td>
                <td>{{ attachment.created }}</td>
                <td class="hidden-print">{% attachment_delete_link attachment %}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">{% trans 'No records found' %}</td>
            </tr>
            {% endfor %}
            </tbody>
            {% if perms.attachments.add_attachment %}
            <tfoot class="hidden-print">
            <tr>
                <th colspan="4">
                    {% attachment_form object %}
                </th>
            </tr>
            </tfoot>
            {% endif %}
        </table>
    </div>
</div>

tcms/templates/include/bug_details.html
{% load i18n %}

{% trans 'Status' %}: {% if object.status %}{% trans 'Open' %}{% else %}{% trans 'Closed' %}{% endif %}

{% trans 'Created on' %}: {{ object.created_at }}

{% trans 'Reporter' %}: {{ object.reporter.username }}

{% if object.assignee %}
    {% trans 'Assignee' %}: {{ object.assignee.username }}
{% endif %}

{% trans 'Product' %}: {{ object.product }}

{% trans 'Version' %}: {{ object.version }}

{% trans 'Build' %}: {{ object.build }}

tcms/templates/include/bugs_table.html
{% load i18n %}
{% load static %}

<div class="col-xs-12 col-sm-6 col-md-4 bugs-table" data-no-records-found-text="{% trans 'No records found' %}">
    <div class="card-pf card-pf-accented">
        <h2 class="card-pf-title">
            <span class="fa fa-bug"></span>
            {{ heading }}
        </h2>

        <div class="card-pf-body">
            <table class="table {{ class }}">
                <thead>
                    <tr>
                        <th colspan="2">{% trans 'URL' %}</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

tcms/templates/include/comments_for_object_template.html
{% load i18n %}

<template id="comment-template">
    <div class="js-comment-container" data-comment-id="">
        <div style="display: flex; justify-content: space-between;">
            <em class="index kiwi-color-gray"></em>
            <strong class="user"></strong>
            <div class="date kiwi-color-gray"></div>
            <a class="js-comment-delete-btn hidden-print"
               href="#" title="{% trans 'Delete' %}">
                <span class="pficon-error-circle-o"></span>
            </a>
        </div>
        <div class="comment" style="overflow: auto"></div>
    </div>
</template>

tcms/templates/include/menu_items.html
{% load extra_filters %}
{% load i18n %}
{% for item in menu_items %}
    {% if not item.1|is_list %}
        {% if item.0 == '-' %}
            <li class="divider"></li>
        {% else %}
        <li>
            <a href="{{ item.1 }}" target="_parent">{{ item.0 }}</a>
        </li>
        {% endif %}
    {% else %}
        {# don't show empty MORE menu #}
        {% if item.1|length > 0 %}
            <li class="dropdown{{ dropdown_class }}">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    {% if item.0 == "..." %}
                        <i class="fa fa-cogs"></i>
                    {% else %}
                        {{ item.0 }}
                    {% endif %}

                    {% if not dropdown_class %}
                    <b class="caret"></b>
                    {% endif %}
                </a>
                <ul class="dropdown-menu">
                    {% include "include/menu_items.html" with menu_items=item.1 dropdown_class="-submenu" %}
                </ul>
            </li>
        {% endif %}
    {% endif %}
{% endfor %}

tcms/templates/include/properties_card.html
{% load i18n %}

<div class="card-pf card-pf-accented">
    <h2 class="card-pf-title">
        <span class="fa fa-cubes"></span>
        {% if card_title %}
            {{ card_title }}
        {% else %}
            {% trans "Parameters" %}
        {% endif %}

        <span class="fa fa-exclamation-triangle help-tooltip kiwi-float-right kiwi-color-warning"
             data-toggle="tooltip"
             data-placement="left"
             title="{% trans 'This is a tech-preview feature!' %}">
        </span>
    </h2>

    <div class="card-pf-body">
        <div class="panel-group" id="properties-accordion">

        <template id="property-fragment">
            <div class="panel panel-no-border">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#properties-accordion" href="#collapseOne"  class="collapsed js-property-name">
                            ---
                        </a>

                        {% if hide_delete_button %}
                        {% else %}
                        <a href="#" class="js-remove-property no-before kiwi-float-right" title="{% trans 'Delete' %}"
                            data-property-name="">
                            <span class="pficon-error-circle-o hidden-print"></span>
                        </a>
                        {% endif %}
                    </h4>
                </div>

                <div id="collapseOne" class="js-panel-collapse panel-collapse collapse">
                    <div class="panel-body js-panel-body">
                        <template>
                            <span class="badge property-value">
                                <span class="js-property-value">---</span>
                                {% if hide_delete_button %}
                                {% else %}
                                <a href="#" title="{% trans 'Delete' %}" class="js-remove-value" data-id="">
                                    <span class="fa fa-times hidden-print"></span>
                                </a>
                                {% endif %}
                            </span>
                        </template>
                    </div>
                </div>
            </div>
        </template>

            <!-- dynamic content needs to be first otherwise expanding doesn't expand the card -->
            <div class="js-insert-here"></div>

            {% if hide_add_button %}
            {% else%}
            <div class="panel panel-no-border hidden-print">
                <div class="panel-heading">
                    <input type="text" class="form-control typeahead" id="property-value-input"
                        style="width: 80%; display: inline"
                        maxlength="255"
                        placeholder="{% trans 'name=value' %}">
                    <a href="#" class="js-add-property-value kiwi-float-right" title="{% trans 'Add' %}">
                        <span class="fa fa-plus hidden-print"></span>
                    </a>
                </div>
            </div>
            {% endif %}
        </div> <!-- panel-group -->
    </div>
</div>

tcms/templates/include/tags_card.html
{% load i18n %}

<div class="card-pf card-pf-accented">
    <h2 class="card-pf-title">
        <span class="fa fa-tags"></span>
        {% trans 'Tags' %}
    </h2>

    <div class="card-pf-body">
        <table class="table" id="tags">
            <thead>
                <tr>
                    <th>{% trans 'Name' %}</th>
                    <th></th>
                </tr>
            </thead>

            {% if add_perm %}
            <tfoot class="hidden-print">
                <tr>
                    <th>
                        <div class="input-group input-group-sm mb-3">
                            <input type="text" class="form-control typeahead" id="id_tags"
                                    maxlength="255">
                        </div>
                    </th>
                    <th>
                        <a href="#tags" id="add-tag" title="{% trans 'Add' %}">
                            <span class="fa fa-plus"></span>
                        </a>
                    </th>
                </tr>
            </tfoot>
            {% endif %}
        </table>
    </div>
</div>